// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0eJxMDDqgs9KWPddM6iUbD4ujv8ZdaNw',
    appId: '1:89153194040:web:8c4604b0b47aabda5ffecd',
    messagingSenderId: '89153194040',
    projectId: 'random-app-9e8bc',
    authDomain: 'random-app-9e8bc.firebaseapp.com',
    storageBucket: 'random-app-9e8bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD8kmqQKFdDLQ1G2semcEQ_oNrWF067SQ',
    appId: '1:89153194040:android:6ef3b169a98d89ec5ffecd',
    messagingSenderId: '89153194040',
    projectId: 'random-app-9e8bc',
    storageBucket: 'random-app-9e8bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATMBfFgyejL6Ht60Arvl-v7197l3L-svQ',
    appId: '1:89153194040:ios:e222ac6c408cf1e25ffecd',
    messagingSenderId: '89153194040',
    projectId: 'random-app-9e8bc',
    storageBucket: 'random-app-9e8bc.appspot.com',
    iosClientId: '89153194040-u2ihc1dqa02so9u0ib1kt7ahh0ph0uhp.apps.googleusercontent.com',
    iosBundleId: 'client.auth.app',
  );
}
